### ISSUE TITLE
Look for reference designs/sample instructional gitbooks

### ISSUE THREAD

**Issue by Ian-Snoddy** [eg4301/Agritech#14]
1. Find 10-20 similar references
2. Identify what is applicable
3. Create table of contents for reference design
4. Start filling out sections (not necessarily chronologically)

**Comment by eg4301** [comment]
1) https://help.supademo.com/?utm_source=marketing_site&utm_medium=referral&utm_campaign=gitbook_library 

Style points (like notion)
But very linear instructions

2) https://handbook.octopus.com/welcome

Good example for us, tutorials are "examples based"
has a section on about us, which we can also take notes from
serve as a baseline

3)https://meshnet.nordvpn.com/?utm_source=marketing_site&utm_medium=referral&utm_campaign=gitbook_library

another example based one, but quite wordy
has a page on features, can use to show how esp32 is good???

4) https://docs.kubecost.com/?utm_source=marketing_site&utm_medium=referral&utm_campaign=gitbook_library

style

**Comment by eg4301** [comment]
Refer to https://nodered.org/docs/tutorials/first-flow

**Comment by eg4301** [comment]
-Write user guide for RAC system
- finish the gitbook
