### ISSUE TITLE
Looking for new peristaltic pump

### ISSUE THREAD

**Issue by eg4301** [eg4301/Agritech#5]
Weizhe

**Comment by eg4301** [comment]
**DONE**
-Pump purchased
-code with pump timer written
**TODO**
-Solder pump to wires
-Connect to relay
-Calibrate

**Comment by Wz-lim** [comment]
DONE
-Solder pump to wires
-Connect to relay
-Calibrate

Peristaltic pump flow rate is 50ml/min
